### ISSUE TITLE
Failed building wheel for pandas

### ISSUE THREAD

**Issue by leimdorfer** [spendnetwork/silvereye#37]
```
ERROR: Failed building wheel for pandas
Successfully built numpy
Failed to build pandas
ERROR: Could not build wheels for pandas which use PEP 517 and cannot be installed directly
```
[Building wheel for pandas (PEP 517) error.txt](https://github.com/spendnetwork/silvereye/files/5568563/Building.wheel.for.pandas.PEP.517.error.txt)

I get this error when I run requirements_dev

**Comment by leimdorfer** [comment]
A manual install of pandas `pip install pandas` and then manually updating the `requirements.txt` to whatever version of pandas it is (in my case 1.1.4) gets you past this problem.

**Comment by SimKennedy** [comment]
These problems are likely due to running python 3.9.
The tool is built on 3.6 and not tested on higher versions. 
The latest numpy and pandas depend on higher than python 3.6.
#40 should address this by pinning pandas/numpy to compatible versions.
